import type { PlaybookVersion } from "../playbook";
import type { ApiKey, GithubSnapshot, Milestone, Project, Task, TaskComment, User } from "../types";

/** The workspace records. Users and API keys are deliberately not included (they stay out of import/export). */
export interface Records {
  tasks: Task[];
  milestones: Milestone[];
  projects: Project[];
  /** Every stored playbook version, pinned or not (a project can be pinned back to any of them). */
  playbooks: PlaybookVersion[];
  /** Records that couldn't be parsed; they're skipped rather than breaking everything. */
  problems: string[];
}

/**
 * GitHub snapshots and task comments: carried by import / export, but not part of loadAll (views read snapshots by key
 * and comments by task).
 */
export interface SnapshotsAndComments {
  /** By key. */
  snapshots: GithubSnapshot[];
  /** By task id, then oldest first. */
  comments: TaskComment[];
  /** Entries that couldn't be parsed; they're skipped rather than breaking everything. */
  problems: string[];
}

/** Records written together: one transaction in Postgres, parents first. */
export interface Changes {
  projects?: Project[];
  milestones?: Milestone[];
  tasks?: Task[];
}

/** A workspace record by its uuid, or by its (uppercase) code. */
export type Key = { id: string } | { code: string };

/**
 * Storage backend behind `src/lib/repo.ts`. Validation, codes and domain rules live in repo.ts;
 * a backend only persists records and hands out numbers. Workspace ids are uuids generated by repo.ts.
 */
export interface Repository {
  readonly kind: "fs" | "postgres";
  /** Settings as stored (defaults not applied), or null when none have been saved. */
  readSettings(): Promise<Record<string, unknown> | null>;
  writeSettings(data: Record<string, unknown>): Promise<void>;
  loadAll(): Promise<Records>;
  getTask(key: Key): Promise<Task | null>;
  getMilestone(key: Key): Promise<Milestone | null>;
  getProject(key: Key): Promise<Project | null>;
  /**
   * Hands out the next `count` numbers for new milestones of a project (`"milestones"`) or new tasks of a
   * milestone (`"tasks"`) by moving the parent's counter, and returns the first. Like a sequence, it isn't
   * rolled back: a failed insert leaves a gap, never a reused number.
   */
  allocateNumbers(kind: "milestones" | "tasks", parentId: string, count: number): Promise<number>;
  /** Stores new records. */
  insert(changes: Changes): Promise<void>;
  /** Overwrites existing records, except the numbering counters (only allocateNumbers moves those). */
  save(changes: Changes): Promise<void>;
  getPlaybookVersion(ref: string): Promise<PlaybookVersion | null>;
  /** Stores a new playbook version; false (nothing written) when its ref is already stored. Versions never change. */
  insertPlaybookVersion(version: PlaybookVersion): Promise<boolean>;
  /** The snapshot stored under a key (`pr:owner/repo#123`, `repo:owner/repo`); null when there is none. */
  getGithubSnapshot(key: string): Promise<GithubSnapshot | null>;
  /** Stores the snapshot whole, replacing whatever was stored under its key. */
  upsertGithubSnapshot(snapshot: GithubSnapshot): Promise<void>;
  /** A task's comments, oldest first (ties by id); empty for an unknown task. */
  listComments(taskId: string): Promise<TaskComment[]>;
  /** Stores a new comment on an existing task. */
  insertComment(comment: TaskComment): Promise<void>;
  /** Deletes one comment of a task; false when the task has no comment with that id. */
  deleteComment(taskId: string, id: string): Promise<boolean>;
  /** Every snapshot and comment, for import / export. */
  loadSnapshotsAndComments(): Promise<SnapshotsAndComments>;
  getUser(id: string): Promise<User | null>;
  /** Exact match; the caller passes an already-normalized email. */
  findUserByEmail(email: string): Promise<User | null>;
  countUsers(): Promise<number>;
  /** Allocates the next U- id and stores the user; null (nothing written) when the email is taken. */
  insertUser(draft: Omit<User, "id">): Promise<User | null>;
  /** Allocates the next K- id and stores the key (its hash only; raw keys are never persisted). */
  insertApiKey(draft: Omit<ApiKey, "id">): Promise<ApiKey>;
  /** Exact match on the lowercase hex SHA-256; revoked keys are returned too (the caller checks revoked_at). */
  findApiKeyByHash(hash: string): Promise<ApiKey | null>;
  /** Every key, revoked ones included, sorted by id number. */
  listApiKeys(): Promise<ApiKey[]>;
  getApiKey(id: string): Promise<ApiKey | null>;
  saveApiKey(key: ApiKey): Promise<void>;
  /**
   * Sets only `last_used_at` (a UTC ISO instant), leaving every other field, `revoked_at` included, as
   * currently stored, so a concurrent revoke is never undone. The updated key, or null for an unknown id.
   */
  touchApiKey(id: string, at: string): Promise<ApiKey | null>;
}

/** The number in a `U-n` / `K-n` id. */
export const idNumber = (id: string) => Number(id.split("-")[1]) || 0;

/** The counter each parent keeps for numbering its children. */
export const COUNTER = { milestones: "last_milestone_number", tasks: "last_task_number" } as const;
